[package]
name = "music_portable_sync"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["cargo"] }
indicatif = { version = "0.17.11", features = ["rayon"] }
itertools = "0.14.0"
miette = { version = "7.5.0", features = ["fancy"] }
rayon = "1.10.0"
thiserror = "2.0.11"
