[package]
name = "music_portable_sync"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.5", features = ["cargo", "derive"] }
indicatif = { version = "0.17.11", features = ["rayon"] }
itertools = "0.14.0"
miette = { version = "7.5.0", features = ["fancy"] }
random-string = "1.1.0"
rapidhash = "1.4.0"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.11"
